choco install git -y
choco install smartgit -y
choco install sourcetree -y
choco install awscli -y
choco install gcloudsdk -y
choco install kubernetes-cli -y
choco install openlens -y
choco install serverless -y
choco install yq -y
choco install jq -y
choco install tree -y
choco install curl -y
choco install microsoft-openjdk17 -y
choco install maven -y
choco install gradle -y
choco install nodejs -y
choco install python3 --pre -y
choco install pyenv-win -y
choco install vscode -y
choco install intellijidea-community -y
choco install dbeaver -y
choco install mongodb-compass -y
choco install vmware-workstation-player -y
choco install postman -y
choco install mitmproxy -y
choco install slack -y
choco install zoom -y
choco install chromium-stable -y
choco install googlechrome -y
choco install docker-desktop -y
